(ns xtrant-crawler.config)

(goog-define VITE_CLERK_PUBLISHABLE_KEY "")
;; (goog-define CLERK_SIGN_IN_URL js/CLERK_SIGN_IN_URL)
;; (goog-define CLERK_SIGN_UP_URL js/CLERK_SIGN_UP_URL)
;; (goog-define CLERK_SIGN_IN_FALLBACK_REDIRECT_URL js/CLERK_SIGN_IN_FALLBACK_REDIRECT_URL)
;; (goog-define CLERK_SIGN_UP_FALLBACK_REDIRECT_URL js/CLERK_SIGN_UP_FALLBACK_REDIRECT_URL)